apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../kubernetes
patches:
  - target:
      kind: Deployment
      name: playbook-flow
    patch: |-
      - op: remove
        path: /spec/template/spec/securityContext/fsGroup
